<?php

namespace App\Http\Requests\Doc;

class WebsiteRequest extends GenericRequest
{
    public function rules()
    {
        $parents = parent::rules(); // TODO: Change the autogenerated stub
        unset($parents['wid']);
        return $parents;
    }
}
