<?php

namespace App\Classes;

abstract class CountryListProvider
{
    public static function data(): array
    {
        return [
            ['id' => '1', 'currency' => 'AFN', 'iso2' => 'AF', 'name' => 'Afghanistan'],
            ['id' => '2', 'currency' => 'ALL', 'iso2' => 'AX', 'name' => 'Albania'],
            ['id' => '3', 'currency' => 'DZD', 'iso2' => 'DZ', 'name' => 'Algeria'],
            ['id' => '4', 'currency' => 'USD', 'iso2' => 'AS', 'name' => 'American Samoa'],
            ['id' => '5', 'currency' => 'EUR', 'iso2' => 'AD', 'name' => 'Andorra'],
            ['id' => '6', 'currency' => 'AOA', 'iso2' => 'AO', 'name' => 'Angola'],
            ['id' => '7', 'currency' => 'XCD', 'iso2' => 'AI', 'name' => 'Anguilla'],
            ['id' => '8', 'currency' => 'AAD', 'iso2' => 'AQ', 'name' => 'Antarctica'],
            ['id' => '9', 'currency' => 'XCD', 'iso2' => 'AG', 'name' => 'Antigua and Barbuda'],
            ['id' => '10', 'currency' => 'ARS', 'iso2' => 'AR', 'name' => 'Argentina'],
            ['id' => '11', 'currency' => 'AMD', 'iso2' => 'AM', 'name' => 'Armenia'],
            ['id' => '12', 'currency' => 'AWG', 'iso2' => 'AW', 'name' => 'Aruba'],
            ['id' => '13', 'currency' => 'AUD', 'iso2' => 'AU', 'name' => 'Australia'],
            ['id' => '14', 'currency' => 'EUR', 'iso2' => 'AT', 'name' => 'Austria'],
            ['id' => '15', 'currency' => 'AZN', 'iso2' => 'AZ', 'name' => 'Azerbaijan'],
            ['id' => '16', 'currency' => 'BSD', 'iso2' => 'BS', 'name' => 'Bahamas The'],
            ['id' => '17', 'currency' => 'BHD', 'iso2' => 'BH', 'name' => 'Bahrain'],
            ['id' => '18', 'currency' => 'BDT', 'iso2' => 'BD', 'name' => 'Bangladesh'],
            ['id' => '19', 'currency' => 'BBD', 'iso2' => 'BB', 'name' => 'Barbados'],
            ['id' => '20', 'currency' => 'BYN', 'iso2' => 'BY', 'name' => 'Belarus'],
            ['id' => '21', 'currency' => 'EUR', 'iso2' => 'BE', 'name' => 'Belgium'],
            ['id' => '22', 'currency' => 'BZD', 'iso2' => 'BZ', 'name' => 'Belize'],
            ['id' => '23', 'currency' => 'XOF', 'iso2' => 'BJ', 'name' => 'Benin'],
            ['id' => '24', 'currency' => 'BMD', 'iso2' => 'BM', 'name' => 'Bermuda'],
            ['id' => '25', 'currency' => 'BTN', 'iso2' => 'BT', 'name' => 'Bhutan'],
            ['id' => '26', 'currency' => 'BOB', 'iso2' => 'BO', 'name' => 'Bolivia'],
            ['id' => '27', 'currency' => 'BAM', 'iso2' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['id' => '28', 'currency' => 'BWP', 'iso2' => 'BW', 'name' => 'Botswana'],
            ['id' => '29', 'currency' => 'NOK', 'iso2' => 'BV', 'name' => 'Bouvet island'],
            ['id' => '30', 'currency' => 'BRL', 'iso2' => 'BR', 'name' => 'Brazil'],
            ['id' => '31', 'currency' => 'USD', 'iso2' => 'IO', 'name' => 'British Indian Ocean Territory'],
            ['id' => '32', 'currency' => 'BND', 'iso2' => 'BN', 'name' => 'Brunei'],
            ['id' => '33', 'currency' => 'BGN', 'iso2' => 'BG', 'name' => 'Bulgaria'],
            ['id' => '34', 'currency' => 'XOF', 'iso2' => 'BF', 'name' => 'Burkina Faso'],
            ['id' => '35', 'currency' => 'BIF', 'iso2' => 'BI', 'name' => 'Burundi'],
            ['id' => '36', 'currency' => 'KHR', 'iso2' => 'KH', 'name' => 'Cambodia'],
            ['id' => '37', 'currency' => 'XAF', 'iso2' => 'CM', 'name' => 'Cameroon'],
            ['id' => '38', 'currency' => 'CAD', 'iso2' => 'CA', 'name' => 'Canada'],
            ['id' => '39', 'currency' => 'CVE', 'iso2' => 'CV', 'name' => 'Cape Verde'],
            ['id' => '40', 'currency' => 'KYD', 'iso2' => 'KY', 'name' => 'Cayman Islands'],
            ['id' => '41', 'currency' => 'XAF', 'iso2' => 'CF', 'name' => 'Central African Republic'],
            ['id' => '42', 'currency' => 'XAF', 'iso2' => 'TD', 'name' => 'Chad'],
            ['id' => '43', 'currency' => 'CLP', 'iso2' => 'CL', 'name' => 'Chile'],
            ['id' => '44', 'currency' => 'CNY', 'iso2' => 'CN', 'name' => 'China'],
            ['id' => '45', 'currency' => 'AUD', 'iso2' => 'CX', 'name' => 'Christmas Island'],
            ['id' => '46', 'currency' => 'AUD', 'iso2' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
            ['id' => '47', 'currency' => 'COP', 'iso2' => 'CO', 'name' => 'Colombia'],
            ['id' => '48', 'currency' => 'KMF', 'iso2' => 'KM', 'name' => 'Comoros'],
            ['id' => '49', 'currency' => 'XAF', 'iso2' => 'CG', 'name' => 'Congo'],
            ['id' => '50', 'currency' => 'CDF', 'iso2' => 'CD', 'name' => 'Democratic Republic of the Congo'],
            ['id' => '51', 'currency' => 'NZD', 'iso2' => 'CK', 'name' => 'Cook Islands'],
            ['id' => '52', 'currency' => 'CRC', 'iso2' => 'CR', 'name' => 'Costa Rica'],
            ['id' => '53', 'currency' => 'XOF', 'iso2' => 'CI', 'name' => 'Cote D\'Ivoire (Ivory Coast)'],
            ['id' => '54', 'currency' => 'HRK', 'iso2' => 'HR', 'name' => 'Croatia (Hrvatska)'],
            ['id' => '55', 'currency' => 'CUP', 'iso2' => 'CU', 'name' => 'Cuba'],
            ['id' => '56', 'currency' => 'EUR', 'iso2' => 'CY', 'name' => 'Cyprus'],
            ['id' => '57', 'currency' => 'CZK', 'iso2' => 'CZ', 'name' => 'Czech Republic'],
            ['id' => '58', 'currency' => 'DKK', 'iso2' => 'DK', 'name' => 'Denmark'],
            ['id' => '59', 'currency' => 'DJF', 'iso2' => 'DJ', 'name' => 'Djibouti'],
            ['id' => '60', 'currency' => 'XCD', 'iso2' => 'DM', 'name' => 'Dominica'],
            ['id' => '61', 'currency' => 'DOP', 'iso2' => 'DO', 'name' => 'Dominican Republic'],
            ['id' => '62', 'currency' => 'USD', 'iso2' => 'TL', 'name' => 'East Timor'],
            ['id' => '63', 'currency' => 'USD', 'iso2' => 'EC', 'name' => 'Ecuador'],
            ['id' => '64', 'currency' => 'EGP', 'iso2' => 'EG', 'name' => 'Egypt'],
            ['id' => '65', 'currency' => 'USD', 'iso2' => 'SV', 'name' => 'El Salvador'],
            ['id' => '66', 'currency' => 'XAF', 'iso2' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['id' => '67', 'currency' => 'ERN', 'iso2' => 'ER', 'name' => 'Eritrea'],
            ['id' => '68', 'currency' => 'EUR', 'iso2' => 'EE', 'name' => 'Estonia'],
            ['id' => '69', 'currency' => 'ETB', 'iso2' => 'ET', 'name' => 'Ethiopia'],
            ['id' => '70', 'currency' => '', 'iso2' => '', 'name' => 'External Territories of Australia'],
            ['id' => '71', 'currency' => 'FKP', 'iso2' => 'FK', 'name' => 'Falkland Islands'],
            ['id' => '72', 'currency' => 'DKK', 'iso2' => 'FO', 'name' => 'Faroe Islands'],
            ['id' => '73', 'currency' => 'FJD', 'iso2' => 'FJ', 'name' => 'Fiji Islands'],
            ['id' => '74', 'currency' => 'EUR', 'iso2' => 'FI', 'name' => 'Finland'],
            ['id' => '75', 'currency' => 'EUR', 'iso2' => 'FR', 'name' => 'France'],
            ['id' => '76', 'currency' => 'EUR', 'iso2' => 'GF', 'name' => 'French Guiana'],
            ['id' => '77', 'currency' => 'XPF', 'iso2' => 'PF', 'name' => 'French Polynesia'],
            ['id' => '78', 'currency' => 'EUR', 'iso2' => 'TF', 'name' => 'French Southern Territories'],
            ['id' => '79', 'currency' => 'XAF', 'iso2' => 'GA', 'name' => 'Gabon'],
            ['id' => '80', 'currency' => 'GMD', 'iso2' => 'GM', 'name' => 'Gambia the'],
            ['id' => '81', 'currency' => 'GEL', 'iso2' => 'GE', 'name' => 'Georgia'],
            ['id' => '82', 'currency' => 'EUR', 'iso2' => 'DE', 'name' => 'Germany'],
            ['id' => '83', 'currency' => 'GHS', 'iso2' => 'GH', 'name' => 'Ghana'],
            ['id' => '84', 'currency' => 'GIP', 'iso2' => 'GI', 'name' => 'Gibraltar'],
            ['id' => '85', 'currency' => 'EUR', 'iso2' => 'GR', 'name' => 'Greece'],
            ['id' => '86', 'currency' => 'DKK', 'iso2' => 'GL', 'name' => 'Greenland'],
            ['id' => '87', 'currency' => 'XCD', 'iso2' => 'GD', 'name' => 'Grenada'],
            ['id' => '88', 'currency' => 'EUR', 'iso2' => 'GP', 'name' => 'Guadeloupe'],
            ['id' => '89', 'currency' => 'USD', 'iso2' => 'GU', 'name' => 'Guam'],
            ['id' => '90', 'currency' => 'GTQ', 'iso2' => 'GT', 'name' => 'Guatemala'],
            ['id' => '91', 'currency' => 'GBP', 'iso2' => 'GG', 'name' => 'Guernsey and Alderney'],
            ['id' => '92', 'currency' => 'GNF', 'iso2' => 'GN', 'name' => 'Guinea'],
            ['id' => '93', 'currency' => 'XOF', 'iso2' => 'GW', 'name' => 'Guinea-Bissau'],
            ['id' => '94', 'currency' => 'GYD', 'iso2' => 'GY', 'name' => 'Guyana'],
            ['id' => '95', 'currency' => 'ince', 'iso2' => 'HT', 'name' => 'Haiti'],
            ['id' => '96', 'currency' => 'AUD', 'iso2' => 'HM', 'name' => 'Heard and Mcdonald Islands'],
            ['id' => '97', 'currency' => 'HNL', 'iso2' => 'HN', 'name' => 'Honduras'],
            ['id' => '98', 'currency' => 'HKD', 'iso2' => 'HK', 'name' => 'Hong Kong S.A.R.'],
            ['id' => '99', 'currency' => 'HUF', 'iso2' => 'HU', 'name' => 'Hungary'],
            ['id' => '100', 'currency' => 'ISK', 'iso2' => 'IS', 'name' => 'Iceland'],
            ['id' => '101', 'currency' => 'INR', 'iso2' => 'IN', 'name' => 'India'],
            ['id' => '102', 'currency' => 'IDR', 'iso2' => 'ID', 'name' => 'Indonesia'],
            ['id' => '103', 'currency' => 'IRR', 'iso2' => 'IR', 'name' => 'Iran'],
            ['id' => '104', 'currency' => 'IQD', 'iso2' => 'IQ', 'name' => 'Iraq'],
            ['id' => '105', 'currency' => 'EUR', 'iso2' => 'IE', 'name' => 'Ireland'],
            ['id' => '106', 'currency' => 'ILS', 'iso2' => 'IL', 'name' => 'Israel'],
            ['id' => '107', 'currency' => 'EUR', 'iso2' => 'IT', 'name' => 'Italy'],
            ['id' => '108', 'currency' => 'JMD', 'iso2' => 'JM', 'name' => 'Jamaica'],
            ['id' => '109', 'currency' => 'JPY', 'iso2' => 'JP', 'name' => 'Japan'],
            ['id' => '110', 'currency' => 'GBP', 'iso2' => 'JE', 'name' => 'Jersey'],
            ['id' => '111', 'currency' => 'JOD', 'iso2' => 'JO', 'name' => 'Jordan'],
            ['id' => '112', 'currency' => 'KZT', 'iso2' => 'KZ', 'name' => 'Kazakhstan'],
            ['id' => '113', 'currency' => 'KES', 'iso2' => 'KE', 'name' => 'Kenya'],
            ['id' => '114', 'currency' => 'AUD', 'iso2' => 'KI', 'name' => 'Kiribati'],
            ['id' => '115', 'currency' => 'KPW', 'iso2' => 'KP', 'name' => 'Korea North'],
            ['id' => '116', 'currency' => 'KRW', 'iso2' => 'KR', 'name' => 'Korea South'],
            ['id' => '117', 'currency' => 'KWD', 'iso2' => 'KW', 'name' => 'Kuwait'],
            ['id' => '118', 'currency' => 'KGS', 'iso2' => 'KG', 'name' => 'Kyrgyzstan'],
            ['id' => '119', 'currency' => 'LAK', 'iso2' => 'LA', 'name' => 'Laos'],
            ['id' => '120', 'currency' => 'EUR', 'iso2' => 'LV', 'name' => 'Latvia'],
            ['id' => '121', 'currency' => 'LBP', 'iso2' => 'LB', 'name' => 'Lebanon'],
            ['id' => '122', 'currency' => 'LSL', 'iso2' => 'LS', 'name' => 'Lesotho'],
            ['id' => '123', 'currency' => 'LRD', 'iso2' => 'LR', 'name' => 'Liberia'],
            ['id' => '124', 'currency' => 'LYD', 'iso2' => 'LY', 'name' => 'Libya'],
            ['id' => '125', 'currency' => 'CHF', 'iso2' => 'LI', 'name' => 'Liechtenstein'],
            ['id' => '126', 'currency' => 'EUR', 'iso2' => 'LT', 'name' => 'Lithuania'],
            ['id' => '127', 'currency' => 'EUR', 'iso2' => 'LU', 'name' => 'Luxembourg'],
            ['id' => '128', 'currency' => 'MOP', 'iso2' => 'MO', 'name' => 'Macau S.A.R.'],
            ['id' => '129', 'currency' => 'MKD', 'iso2' => 'MK', 'name' => 'Macedonia'],
            ['id' => '130', 'currency' => 'MGA', 'iso2' => 'MG', 'name' => 'Madagascar'],
            ['id' => '131', 'currency' => 'MWK', 'iso2' => 'MW', 'name' => 'Malawi'],
            ['id' => '132', 'currency' => 'MYR', 'iso2' => 'MY', 'name' => 'Malaysia'],
            ['id' => '133', 'currency' => 'MVR', 'iso2' => 'MV', 'name' => 'Maldives'],
            ['id' => '134', 'currency' => 'XOF', 'iso2' => 'ML', 'name' => 'Mali'],
            ['id' => '135', 'currency' => 'EUR', 'iso2' => 'MT', 'name' => 'Malta'],
            ['id' => '136', 'currency' => 'GBP', 'iso2' => 'IM', 'name' => 'Man (Isle Of)'],
            ['id' => '137', 'currency' => 'USD', 'iso2' => 'MH', 'name' => 'Marshall Islands'],
            ['id' => '138', 'currency' => 'EUR', 'iso2' => 'MQ', 'name' => 'Martinique'],
            ['id' => '139', 'currency' => 'MRO', 'iso2' => 'MR', 'name' => 'Mauritania'],
            ['id' => '140', 'currency' => 'MUR', 'iso2' => 'MU', 'name' => 'Mauritius'],
            ['id' => '141', 'currency' => 'EUR', 'iso2' => 'YT', 'name' => 'Mayotte'],
            ['id' => '142', 'currency' => 'MXN', 'iso2' => 'MX', 'name' => 'Mexico'],
            ['id' => '143', 'currency' => 'USD', 'iso2' => 'FM', 'name' => 'Micronesia'],
            ['id' => '144', 'currency' => 'MDL', 'iso2' => 'MD', 'name' => 'Moldova'],
            ['id' => '145', 'currency' => 'EUR', 'iso2' => 'MC', 'name' => 'Monaco'],
            ['id' => '146', 'currency' => 'MNT', 'iso2' => 'MN', 'name' => 'Mongolia'],
            ['id' => '147', 'currency' => 'XCD', 'iso2' => 'MS', 'name' => 'Montserrat'],
            ['id' => '148', 'currency' => 'MAD', 'iso2' => 'MA', 'name' => 'Morocco'],
            ['id' => '149', 'currency' => 'MZN', 'iso2' => 'MZ', 'name' => 'Mozambique'],
            ['id' => '150', 'currency' => 'MMK', 'iso2' => 'MM', 'name' => 'Myanmar'],
            ['id' => '151', 'currency' => 'NAD', 'iso2' => 'NA', 'name' => 'Namibia'],
            ['id' => '152', 'currency' => 'AUD', 'iso2' => 'NR', 'name' => 'Nauru'],
            ['id' => '153', 'currency' => 'NPR', 'iso2' => 'NP', 'name' => 'Nepal'],
            ['id' => '154', 'currency' => 'EUR', 'iso2' => 'NL', 'name' => 'Netherlands Antilles'],
            ['id' => '155', 'currency' => 'EUR', 'iso2' => 'NL', 'name' => 'Netherlands The'],
            ['id' => '156', 'currency' => 'XPF', 'iso2' => 'NC', 'name' => 'New Caledonia'],
            ['id' => '157', 'currency' => 'NZD', 'iso2' => 'NZ', 'name' => 'New Zealand'],
            ['id' => '158', 'currency' => 'NIO', 'iso2' => 'NI', 'name' => 'Nicaragua'],
            ['id' => '159', 'currency' => 'XOF', 'iso2' => 'NE', 'name' => 'Niger'],
            ['id' => '160', 'currency' => 'NGN', 'iso2' => 'NG', 'name' => 'Nigeria'],
            ['id' => '161', 'currency' => 'NZD', 'iso2' => 'NU', 'name' => 'Niue'],
            ['id' => '162', 'currency' => 'AUD', 'iso2' => 'NF', 'name' => 'Norfolk Island'],
            ['id' => '163', 'currency' => 'USD', 'iso2' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['id' => '164', 'currency' => 'NOK', 'iso2' => 'NO', 'name' => 'Norway'],
            ['id' => '165', 'currency' => 'OMR', 'iso2' => 'OM', 'name' => 'Oman'],
            ['id' => '166', 'currency' => 'PKR', 'iso2' => 'PK', 'name' => 'Pakistan'],
            ['id' => '167', 'currency' => 'USD', 'iso2' => 'PW', 'name' => 'Palau'],
            ['id' => '168', 'currency' => 'ILS', 'iso2' => 'PS', 'name' => 'Palestinian Territory Occupied'],
            ['id' => '169', 'currency' => 'PAB', 'iso2' => 'PA', 'name' => 'Panama'],
            ['id' => '170', 'currency' => 'PGK', 'iso2' => 'PG', 'name' => 'Papua New Guinea'],
            ['id' => '171', 'currency' => 'PYG', 'iso2' => 'PY', 'name' => 'Paraguay'],
            ['id' => '172', 'currency' => 'PEN', 'iso2' => 'PE', 'name' => 'Peru'],
            ['id' => '173', 'currency' => 'PHP', 'iso2' => 'PH', 'name' => 'Philippines'],
            ['id' => '174', 'currency' => 'NZD', 'iso2' => 'PN', 'name' => 'Pitcairn Island'],
            ['id' => '175', 'currency' => 'PLN', 'iso2' => 'PL', 'name' => 'Poland'],
            ['id' => '176', 'currency' => 'EUR', 'iso2' => 'PT', 'name' => 'Portugal'],
            ['id' => '177', 'currency' => 'USD', 'iso2' => 'PR', 'name' => 'Puerto Rico'],
            ['id' => '178', 'currency' => 'QAR', 'iso2' => 'QA', 'name' => 'Qatar'],
            ['id' => '179', 'currency' => 'EUR', 'iso2' => 'RE', 'name' => 'Reunion'],
            ['id' => '180', 'currency' => 'RON', 'iso2' => 'RO', 'name' => 'Romania'],
            ['id' => '181', 'currency' => 'RUB', 'iso2' => 'RU', 'name' => 'Russia'],
            ['id' => '182', 'currency' => 'RWF', 'iso2' => 'RW', 'name' => 'Rwanda'],
            ['id' => '183', 'currency' => 'SHP', 'iso2' => 'SH', 'name' => 'Saint Helena'],
            ['id' => '184', 'currency' => 'XCD', 'iso2' => 'KN', 'name' => 'Saint Kitts and Nevis'],
            ['id' => '185', 'currency' => 'XCD', 'iso2' => 'LC', 'name' => 'Saint lucia'],
            ['id' => '186', 'currency' => 'EUR', 'iso2' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
            ['id' => '187', 'currency' => 'XCD', 'iso2' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
            ['id' => '188', 'currency' => 'WST', 'iso2' => 'WS', 'name' => 'Samoa'],
            ['id' => '189', 'currency' => 'EUR', 'iso2' => 'SM', 'name' => 'San Marino'],
            ['id' => '190', 'currency' => 'STD', 'iso2' => 'ST', 'name' => 'Sao Tome and Principe'],
            ['id' => '191', 'currency' => 'SAR', 'iso2' => 'SA', 'name' => 'Saudi arabia'],
            ['id' => '192', 'currency' => 'XOF', 'iso2' => 'SN', 'name' => 'Senegal'],
            ['id' => '193', 'currency' => 'RSD', 'iso2' => 'RS', 'name' => 'Serbia'],
            ['id' => '194', 'currency' => 'SCR', 'iso2' => 'SC', 'name' => 'Seychelles'],
            ['id' => '195', 'currency' => 'SLL', 'iso2' => 'SL', 'name' => 'Sierra Leone'],
            ['id' => '196', 'currency' => 'SGD', 'iso2' => 'SG', 'name' => 'Singapore'],
            ['id' => '197', 'currency' => 'EUR', 'iso2' => 'SK', 'name' => 'Slovakia'],
            ['id' => '198', 'currency' => 'EUR', 'iso2' => 'SI', 'name' => 'Slovenia'],
            ['id' => '199', 'currency' => '', 'iso2' => '', 'name' => 'Smaller Territories of the UK'],
            ['id' => '200', 'currency' => 'SBD', 'iso2' => 'SB', 'name' => 'Solomon Islands'],
            ['id' => '201', 'currency' => 'SOS', 'iso2' => 'SO', 'name' => 'Somalia'],
            ['id' => '202', 'currency' => 'ZAR', 'iso2' => 'ZA', 'name' => 'South Africa'],
            ['id' => '203', 'currency' => 'GBP', 'iso2' => 'GS', 'name' => 'South Georgia'],
            ['id' => '204', 'currency' => 'SSP', 'iso2' => 'SS', 'name' => 'South Sudan'],
            ['id' => '205', 'currency' => 'EUR', 'iso2' => 'ES', 'name' => 'Spain'],
            ['id' => '206', 'currency' => 'LKR', 'iso2' => 'LK', 'name' => 'Sri Lanka'],
            ['id' => '207', 'currency' => 'SDG', 'iso2' => 'SD', 'name' => 'Sudan'],
            ['id' => '208', 'currency' => 'SRD', 'iso2' => 'SR', 'name' => 'Suriname'],
            ['id' => '209', 'currency' => 'NOK', 'iso2' => 'SJ', 'name' => 'Svalbard and Jan Mayen Islands'],
            ['id' => '210', 'currency' => 'SZL', 'iso2' => 'SZ', 'name' => 'Swaziland'],
            ['id' => '211', 'currency' => 'SEK', 'iso2' => 'SE', 'name' => 'Sweden'],
            ['id' => '212', 'currency' => 'CHF', 'iso2' => 'CH', 'name' => 'Switzerland'],
            ['id' => '213', 'currency' => 'SYP', 'iso2' => 'SY', 'name' => 'Syria'],
            ['id' => '214', 'currency' => 'TWD', 'iso2' => 'TW', 'name' => 'Taiwan'],
            ['id' => '215', 'currency' => 'TJS', 'iso2' => 'TJ', 'name' => 'Tajikistan'],
            ['id' => '216', 'currency' => 'TZS', 'iso2' => 'TZ', 'name' => 'Tanzania'],
            ['id' => '217', 'currency' => 'THB', 'iso2' => 'TH', 'name' => 'Thailand'],
            ['id' => '218', 'currency' => 'XOF', 'iso2' => 'TG', 'name' => 'Togo'],
            ['id' => '219', 'currency' => 'NZD', 'iso2' => 'TK', 'name' => 'Tokelau'],
            ['id' => '220', 'currency' => 'TOP', 'iso2' => 'TO', 'name' => 'Tonga'],
            ['id' => '221', 'currency' => 'TTD', 'iso2' => 'TT', 'name' => 'Trinidad and Tobago'],
            ['id' => '222', 'currency' => 'TND', 'iso2' => 'TN', 'name' => 'Tunisia'],
            ['id' => '223', 'currency' => 'TRY', 'iso2' => 'TR', 'name' => 'Turkey'],
            ['id' => '224', 'currency' => 'TMT', 'iso2' => 'TM', 'name' => 'Turkmenistan'],
            ['id' => '225', 'currency' => 'USD', 'iso2' => 'TC', 'name' => 'Turks and Caicos Islands'],
            ['id' => '226', 'currency' => 'AUD', 'iso2' => 'TV', 'name' => 'Tuvalu'],
            ['id' => '227', 'currency' => 'UGX', 'iso2' => 'UG', 'name' => 'Uganda'],
            ['id' => '228', 'currency' => 'UAH', 'iso2' => 'UA', 'name' => 'Ukraine'],
            ['id' => '229', 'currency' => 'AED', 'iso2' => 'AE', 'name' => 'United Arab Emirates'],
            ['id' => '230', 'currency' => 'GBP', 'iso2' => 'GB', 'name' => 'United Kingdom'],
            ['id' => '231', 'currency' => 'USD', 'iso2' => 'US', 'name' => 'United States'],
            ['id' => '232', 'currency' => 'USD', 'iso2' => 'UM', 'name' => 'United States Minor Outlying Islands'],
            ['id' => '233', 'currency' => 'UYU', 'iso2' => 'UY', 'name' => 'Uruguay'],
            ['id' => '234', 'currency' => 'UZS', 'iso2' => 'UZ', 'name' => 'Uzbekistan'],
            ['id' => '235', 'currency' => 'VUV', 'iso2' => 'VU', 'name' => 'Vanuatu'],
            ['id' => '236', 'currency' => 'EUR', 'iso2' => 'VA', 'name' => 'Vatican City State (Holy See)'],
            ['id' => '237', 'currency' => 'VEF', 'iso2' => 'VE', 'name' => 'Venezuela'],
            ['id' => '238', 'currency' => 'VND', 'iso2' => 'VN', 'name' => 'Vietnam'],
            ['id' => '239', 'currency' => 'USD', 'iso2' => 'VG', 'name' => 'Virgin Islands (British)'],
            ['id' => '240', 'currency' => 'USD', 'iso2' => 'VI', 'name' => 'Virgin Islands (US)'],
            ['id' => '241', 'currency' => 'XPF', 'iso2' => 'WF', 'name' => 'Wallis and Futuna Islands'],
            ['id' => '242', 'currency' => 'MAD', 'iso2' => 'EH', 'name' => 'Western Sahara'],
            ['id' => '243', 'currency' => 'YER', 'iso2' => 'YE', 'name' => 'Yemen'],
            ['id' => '244', 'currency' => 'YUM', 'iso2' => 'YU', 'name' => 'Yugoslavia'],
            ['id' => '245', 'currency' => 'ZMW', 'iso2' => 'ZM', 'name' => 'Zambia'],
            ['id' => '246', 'currency' => 'ZWL', 'iso2' => 'ZW', 'name' => 'Zimbabwe']
        ];
    }
}
